services:
  - type: web
    name: realestate-ai-agent
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    envVars:
      - key: BROWSER_HEADED
        value: false
      - key: BROWSER_DEVTOOLS
        value: false
      - key: BROWSER_ENGINE
        value: chromium
