#!/usr/bin/env python3
"""Generate docs/reference/agents-and-tools.md from the tool registry.

Reads the live registry (GET /api/tools/registry) when the backend is up,
else falls back to neurosan/tool_schemas.json. Keeps docs in lockstep with
code, same philosophy as neurosan/generate_network.py.

    python3 scripts/gen_tool_docs.py
"""
import json
import os
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SNAPSHOT = os.path.join(ROOT, "neurosan", "tool_schemas.json")
OUT = os.path.join(ROOT, "docs", "reference", "agents-and-tools.md")

# Mirrors neurosan/generate_network.py SPECIALISTS and
# orchestrator/src/langgraph/specialists.ts — one team, two engines.
SPECIALISTS = [
    ("property_scout", "Property Scout", "Sources and screens deals: marketplace search, listing analysis, comps, ranking.",
     ["search_properties", "analyze_property_url", "comp_analysis", "filter_and_rank"]),
    ("risk_analyst", "Risk Analyst", "The team's skeptic: market/deal risk scoring, tenant credit, risk decomposition.",
     ["assess_risk", "score_deals", "tenant_credit_analysis", "risk_decomposition"]),
    ("market_analyst", "Market Analyst", "Macro and local context: FRED/BLS data, metro deep dives, market intel, foot traffic.",
     ["get_macro_data", "market_deep_dive", "market_intel", "analyze_traffic_patterns"]),
    ("financial_modeler", "Financial Modeler", "DCF valuation with stated assumptions; multi-asset comparison.",
     ["run_dcf", "multi_asset_compare"]),
    ("portfolio_manager", "Portfolio Manager", "Portfolio-level view: review, VaR, compliance/allocation, pipeline.",
     ["portfolio_review", "portfolio_var", "compliance_check", "institutional_pipeline"]),
    ("deal_writer", "Deal Writer", "Investment documents: IC memos and LOIs, written only from supplied facts.",
     ["generate_memo", "generate_loi"]),
]


def load_schemas():
    try:
        with urllib.request.urlopen("http://localhost:3001/api/tools/registry", timeout=5) as r:
            tools = json.load(r)["tools"]
        print(f"Loaded {len(tools)} tools from live registry")
        return {t["name"]: t for t in tools}
    except Exception as e:
        print(f"Backend not reachable ({e}); using snapshot")
        with open(SNAPSHOT) as f:
            snap = json.load(f)
        return {k: {"name": k, **v} for k, v in snap.items()}


def param_rows(parameters):
    props = parameters.get("properties", {})
    required = set(parameters.get("required", []))
    rows = []
    for name, p in props.items():
        t = p.get("type", "any")
        if t == "array":
            t = f"array<{(p.get('items') or {}).get('type', 'any')}>"
        req = "✓" if name in required else ""
        desc = (p.get("description") or "").replace("|", "\\|")
        rows.append(f"| `{name}` | {t} | {req} | {desc} |")
    return rows


def main():
    schemas = load_schemas()
    lines = [
        "# Agents & Tools",
        "",
        "<!-- GENERATED by scripts/gen_tool_docs.py — do not edit by hand. -->",
        "",
        "The agent team: one supervisor (`deal_advisor`) over six specialists and "
        f"{len(schemas)} tools. The same definitions drive **both** orchestrators "
        "(generated HOCON for Neuro SAN, `specialists.ts` for LangGraph.js).",
        "",
        "Every tool below executes as a **zero-token API call** via "
        "`POST /api/tools/execute` — deterministic, unit-testable, LLM-free.",
        "",
    ]
    for sid, label, desc, tools in SPECIALISTS:
        lines += [f"## {label} (`{sid}`)", "", desc, ""]
        for t in tools:
            s = schemas.get(t)
            if not s:
                lines += [f"### `{t}`", "", "_Not found in registry._", ""]
                continue
            lines += [
                f"### `{t}`",
                "",
                s.get("description", ""),
                "",
                f"*Category: `{s.get('category', '—')}`*",
                "",
            ]
            rows = param_rows(s.get("parameters") or {})
            if rows:
                lines += ["| Parameter | Type | Required | Description |",
                          "|---|---|---|---|", *rows, ""]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
